## Scraping TVs Data from Kilimall

### 1. Importing Libraries

In [2]:

import time
import requests
from bs4 import BeautifulSoup
import pandas as pd

### 2. Describing the base url and user agent variables

In [3]:
# setting the base url & user agent
baseurl = "https://www.kilimall.co.ke/"
headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6439.0 AOL/9.7 AOLBuild/4343.4043.US Safari/537.36'}

### 3. A loop that iterates through the website, scrapes data


#### (a) Scraping tv data with ratings

In [11]:
# getting data with product link
tv_links = []

for x in range(1,6):
    r = requests.get(f"https://www.kilimall.co.ke/category/televisions?backCid=5406&form=category&source=category|allCategory|televisions&page={x}")
    soup = BeautifulSoup(r.content, "html.parser")
    television_list = soup.find_all("div", class_ = "product-item")

    for television in television_list:
        for link in television.find_all("a", href = True):
            tv_links.append(baseurl + link["href"])

print(len(tv_links))

180

In [12]:
# write the list to a txt file
with open ("tv_links.txt", "w") as file:
    for item in tv_links:
        file.write(f"{item}\n")

In [13]:
# getting data from the link
#tv_link_txt = r"tv_links.txt"

#image_link = "https://www.kilimall.co.ke/listing/2517665-vitron-32-inch-frameless-smart-tv-hd-netflix-tv-htc3200s-youtube-television-dvbt2-android-11-ac-energy-saving-television-1g8g?skuId=18272411"

product_list_tv = []

for link in tv_links[0:10]:
    print("saving:" + str(tv_links.index(link)))
    r = requests.get(link, headers=headers)
    soup = BeautifulSoup(r.content, "html.parser")

    product_id = soup.find("div", class_ = "last-b-name name").text.strip()
    name = soup.find("div", class_ = "product-title").text.strip()
    current_price = soup.find("span", class_ = "sale-price").text.strip()
    previous_price = soup.find("span", class_ = "del-price").text.strip()
    reviews = soup.find("span", class_ = "reviews").text.strip()
    rating = soup.find("span", class_ = "rate").text.strip()
    
    
    # define a dictionary
    tvs_dict = {
        'product_id': product_id,
        'name': name,
        "rating": rating,
        "reviews": reviews,
        "current_price": current_price,
        "previous_price": previous_price
    }

    product_list_tv.append(tvs_dict)
    
    # Wait for 5 seconds before the next request
    time.sleep(5)

saving:0
saving:1
saving:2
saving:3
saving:4
saving:5
saving:6
saving:7
saving:8
saving:9

In [14]:
df = pd.DataFrame(product_list_tv)
df

,product_id,name,rating,reviews,current_price,previous_price
0,SKU ID: 18272411,Vitron 32 Inch Frameless Smart TV HD Netflix T...,5.0,0 Customer reviews,"KSh 11,199","KSh15,999"
1,SKU ID: 18257587,Vitron 32 inch Frameless Television HTC 3218 L...,5.0,0 Customer reviews,"KSh 11,099","KSh13,999"
2,SKU ID: 17369128,Vitron 43 inch Smart TV HTC 4388FS Android Tel...,5.0,0 Customer reviews,"KSh 18,499","KSh37,999"
3,SKU ID: 18285104,"VITRON BLUETOOTH-ENABLED 32"" INCH HTC3200S,FRA...",5.0,0 Customer reviews,"KSh 13,978","KSh 17,000"
4,SKU ID: 15343058,"VITRON 32"" Inch DIGITAL TELEVISION FRAMELESS H...",5.0,0 Customer reviews,"KSh 12,998","KSh 16,500"
5,SKU ID: 17640653,GLD 32 Inch Frameless Smart Android TV（G3200R1...,5.0,0 Customer reviews,"KSh 11,799","KSh 19,999"
6,SKU ID: 16624308,"BLUETOOTH VITRON HTC4388FS 43"" INCH FRAMELESS...",5.0,0 Customer reviews,"KSh 22,790","KSh 26,500"
7,SKU ID: 10000602610,(Special offer)Artel 32 inch Frameless Bluetoo...,5.0,0 Customer reviews,"KSh 11,099","KSh 15,000"
8,SKU ID: 10001041407,Artel 30AT2801 Digital AC/DC TV Original 1080P...,5.0,0 Customer reviews,"KSh 8,499","KSh 10,800"
9,SKU ID: 15423226,"VITRON 43"" INCH BLUETOOTH ENABLED HTC4388FS FR...",5.0,0 Customer reviews,"KSh 21,799","KSh 26,500"

In [55]:
# save as csv
df.to_csv("kilimall_tvs.csv", index = False, encoding = "utf-8")

In [58]:
test_link = "https://www.kilimall.co.ke/listing/2199368-bluetooth-vitron-htc4388fs-43-inch-frameless-fhd-smart-tv-android-tv-netflix-youtube-television-inbuilt-decoder-builtin-wifi-app-store-1gbram-8gbrom-2usb-ports3hdmi-ports-7-free-gifts?skuId=16624308&source=category-allCategory-televisions"

r = requests.get(test_link, headers=headers)
soup = BeautifulSoup(r.content, "html.parser")

product_id = soup.find("div", class_ = "last-b-name name").text.strip()
name = soup.find("div", class_ = "product-title").text.strip()
current_price = soup.find("span", class_ = "sale-price").text.strip()
previous_price = soup.find("span", class_ = "del-price").text.strip()
reviews = soup.find("span", class_ = "reviews").text.strip()
rating = soup.find("span", class_ = "rate").text.strip()
    
# define a dictionary
tvs_dict = {
    "product_id": product_id,
    "name": name,
    "rating": rating,
    "reviews": reviews,
    "current_price": current_price,
    "previous_price": previous_price
    }

print(tvs_dict)

{'product_id': 'SKU ID: 16624308', 'name': 'BLUETOOTH VITRON HTC4388FS 43" INCH  FRAMELESS FHD SMART TV ANDROID TV NETFLIX ,YOUTUBE TELEVISION INBUILT DECODER , BUILT-IN WIFI, APP STORE 1GB-RAM 8GB-ROM 2*USB PORTS,3*HDMI PORTS + 7 FREE GIFTS', 'rating': '5.0', 'reviews': '0 Customer reviews', 'current_price': 'KSh 22,790', 'previous_price': 'KSh 26,500'}

__Comments__
- Retrieving the rating and number of reviews directly from individual product links was not feasible because the HTML tags consistently output all products as having a 5-star rating with 0 customer reviews.
- This output conflicts with the actual information visible on the webpage, indicating a possible discrepancy between the HTML data and the rendered content. This might be due to the website using dynamic content (e.g., JavaScript) that is not fully captured during scraping.

#### (b) scraping tv data without ratings

In [31]:
tv_list_no_rating = []
for x in range(1,119):
    print("saving:" + str(x))
    r = requests.get(f"https://www.kilimall.co.ke/category/televisions?backCid=5406&form=category&source=category|allCategory|televisions&page={x}")
    soup = BeautifulSoup(r.content, "html.parser")
    television_list = soup.find_all("div", class_ = "info-box")

    for item in television_list:
        product_name = item.find("p", class_ = "product-title").text.strip()
        product_price = item.find("div", class_ = "product-price").text.strip()
        product_reviews = item.find("span", class_ = "reviews").text.strip()
        # define a dictionary
        tvs_dict = {
            "product_name": product_name,
            "product_reviews": product_reviews,
            "product_price": product_price,
            }
        tv_list_no_rating.append(tvs_dict)
print(len(tv_list_no_rating))

        # define a dictionary
        #tvs_dict = {
            #"product_name": product_name,
            #"product_reviews": product_reviews,
            #"product_price": product_price,
            #}
        #tv_list_no_rating.append(tvs_dict)

saving:1
saving:2
saving:3
saving:4
saving:5
saving:6
saving:7
saving:8
saving:9
saving:10
saving:11
saving:12
saving:13
saving:14
saving:15
saving:16
saving:17
saving:18
saving:19
saving:20
saving:21
saving:22
saving:23
saving:24
saving:25
saving:26
saving:27
saving:28
saving:29
saving:30
saving:31
saving:32
saving:33
saving:34
saving:35
saving:36
saving:37
saving:38
saving:39
saving:40
saving:41
saving:42
saving:43
saving:44
saving:45
saving:46
saving:47
saving:48
saving:49
saving:50
saving:51
saving:52
saving:53
saving:54
saving:55
saving:56
saving:57
saving:58
saving:59
saving:60
saving:61
saving:62
saving:63
saving:64
saving:65
saving:66
saving:67
saving:68
saving:69
saving:70
saving:71
saving:72
saving:73
saving:74
saving:75
saving:76
saving:77
saving:78
saving:79
saving:80
saving:81
saving:82
saving:83
saving:84
saving:85
saving:86
saving:87
saving:88
saving:89
saving:90
saving:91
saving:92
saving:93
saving:94
saving:95
saving:96
saving:97
saving:98
saving:99
saving:100
saving:101
saving:102
saving:103
saving:104
saving:105
saving:106
saving:107
saving:108
saving:109
saving:110
saving:111
saving:112
saving:113
saving:114
saving:115
saving:116
saving:117
saving:118
4239

In [32]:
#convert the list to df

tvs_no_rating_df = pd.DataFrame(tv_list_no_rating)
tvs_no_rating_df

,product_name,product_reviews,product_price
0,Vitron 32 Inch Frameless Smart TV HD Netflix T...,(1347),"KSh 11,199"
1,Vitron 32 inch Frameless Television HTC 3218 L...,(710),"KSh 11,099"
2,Vitron 43 inch Smart TV HTC 4388FS Android Tel...,(1142),"KSh 18,499"
3,"VITRON BLUETOOTH-ENABLED 32"" INCH HTC3200S,FRA...",(947),"KSh 13,978"
4,"VITRON 32"" Inch DIGITAL TELEVISION FRAMELESS H...",(243),"KSh 12,998"
...,...,...,...
4234,"TV 24"" Inch LED Digital HD TV + 6 Free Gifts D...",(1),"KSh 11,999"
4235,Vitron 32 Inch Frameless Smart TV HD Netflix T...,(1),"KSh 12,999"
4236,CTC 22 Inch HD Digital LED TV With Inbuilt Dec...,(1),"KSh 7,500"
4237,"Gld 32''INCH ,Frameless 32Inch Smart Android T...",(1),"KSh 14,999"
4238,"Samsung 32T5300 32"" Smart Full HD TV HDR Serie...",(1),"KSh 28,399"

In [33]:
# save as csv
tvs_no_rating_df.to_csv("kilimall_tvs_no_rating.csv", index = False, encoding = "utf-8")