In [1]:
import time
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
phones_list_no_rating = [] # initializing an empty list that will store the results of the for loop

for x in range(1,150): # range of website pages that has phones product displayed on them
    print("saving:" + str(x))
    r_phones = requests.get(f"https://www.kilimall.co.ke/search?q=phones&page={x}&source=search|enterSearch|phones")

    soup_phones = BeautifulSoup(r_phones.content, "html.parser")
    phones_list = soup_phones.find_all("div", class_ = "info-box")
    #print(phones_list)
    for item in phones_list:
        try:
            phones_name = item.find("p", class_ = "product-title").text.strip()
            phones_price = item.find("div", class_ = "product-price").text.strip()
            phones_reviews = item.find("span", class_ = "reviews").text.strip()
        except AttributeError:
            # Handle missing data
           phones_name = "N/A"
           phones_price = "N/A"
           phones_reviews = "N/A"
                # define a dictionary
        phones_dict = {
            "phones_name": phones_name,
            "phones_reviews": phones_reviews,
            "phones_price": phones_price,
            }
        phones_list_no_rating.append(phones_dict)

print(len(phones_list_no_rating)) # checks the number of cooktops saved in this list

saving:1
saving:2
saving:3
saving:4
saving:5
saving:6
saving:7
saving:8
saving:9
saving:10
saving:11
saving:12
saving:13
saving:14
saving:15
saving:16
saving:17
saving:18
saving:19
saving:20
saving:21
saving:22
saving:23
saving:24
saving:25
saving:26
saving:27
saving:28
saving:29
saving:30
saving:31
saving:32
saving:33
saving:34
saving:35
saving:36
saving:37
saving:38
saving:39
saving:40
saving:41
saving:42
saving:43
saving:44
saving:45
saving:46
saving:47
saving:48
saving:49
saving:50
saving:51
saving:52
saving:53
saving:54
saving:55
saving:56
saving:57
saving:58
saving:59
saving:60
saving:61
saving:62
saving:63
saving:64
saving:65
saving:66
saving:67
saving:68
saving:69
saving:70
saving:71
saving:72
saving:73
saving:74
saving:75
saving:76
saving:77
saving:78
saving:79
saving:80
saving:81
saving:82
saving:83
saving:84
saving:85
saving:86
saving:87
saving:88
saving:89
saving:90
saving:91
saving:92
saving:93
saving:94
saving:95
saving:96
saving:97
saving:98
saving:99
saving:100
saving:101
saving:102
saving:103
saving:104
saving:105
saving:106
saving:107
saving:108
saving:109
saving:110
saving:111
saving:112
saving:113
saving:114
saving:115
saving:116
saving:117
saving:118
saving:119
saving:120
saving:121
saving:122
saving:123
saving:124
saving:125
saving:126
saving:127
saving:128
saving:129
saving:130
saving:131
saving:132
saving:133
saving:134
saving:135
saving:136
saving:137
saving:138
saving:139
saving:140
saving:141
saving:142
saving:143
saving:144
saving:145
saving:146
saving:147
saving:148
saving:149
5364

In [3]:
phones_df = pd.DataFrame(phones_list_no_rating)
phones_df

,phones_name,phones_reviews,phones_price
0,Refurbished OPPO F11 A9 Smart Phone 128GB+6GB ...,(18),"KSh 7,499"
1,Itel S23 Plus 128GB + 8(4+4)GB RAM 6.78'' Big ...,(165),"KSh 13,599"
2,XIAOMI Redmi 14C 128GB Storage Upto 8(4+4)GB R...,(149),"KSh 12,910"
3,New Arrival TECNO POP 9 128GB + 6(3+3)GB 4.5G ...,(87),"KSh 11,499"
4,"Itel A70 128GB+8(3+5)GB RAM 6.6"" Screen 4G Ne...",(578),"KSh 9,799"
...,...,...,...
5359,"Share this product\n\n\nVILLAON V20 SE 5.0"" 4G...",(0),"KSh 4,999"
5360,"Share this product\n\n\nVILLAON V20 SE 5.0"" 4G...",(0),"KSh 4,999"
5361,"Share this product\n\n\nVILLAON V20 SE 5.0"" 4G...",(0),"KSh 4,999"
5362,Iphone 11 pro max,(0),"KSh 40,000"
5363,"XIAOMI Redmi Note 13 6.67"" 8GB RAM/256 GB ROM ...",(0),"KSh 26,000"

In [4]:
phones_df.to_csv("kilimall_scraped_phones.csv", index = False, encoding = "utf-8")